version = 0.1

[default.deploy.parameters]
stack_name = "ecr-ecs-web-app-stack"
resolve_s3 = true
s3_prefix = "ecr-ecs-web-app-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "ImageUri=\"nginx\" DesiredCount=\"2\" ContainerPort=\"80\" EcrRepositoryName=\"ecr-ecs-web-app\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
